# Generated by Django 5.0.4 on 2024-05-06 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0002_interest_table_fd_account_model_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_account_model',
            name='interest',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
