# Generated by Django 5.0.4 on 2024-05-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0003_fd_account_model_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest_table',
            name='period',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
