# Generated by Django 5.0.4 on 2024-05-06 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0004_interest_table_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fd_account_model',
            old_name='balance',
            new_name='amount',
        ),
    ]
