# Generated by Django 5.0.4 on 2024-05-06 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0006_alter_fd_account_model_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_account_model',
            name='open_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='fd_account_model',
            name='tenure',
            field=models.IntegerField(),
        ),
    ]
