# Generated by Django 5.0.4 on 2024-05-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0007_fd_account_model_open_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_account_model',
            name='interest_type',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
