# Generated by Django 5.0.4 on 2024-05-06 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0008_fd_account_model_interest_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fd_account_model',
            old_name='interest_type',
            new_name='interest_period',
        ),
    ]
