# Generated by Django 5.0.4 on 2024-05-06 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0009_rename_interest_type_fd_account_model_interest_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fd_account_model',
            old_name='amount',
            new_name='Deposit_amount',
        ),
        migrations.RenameField(
            model_name='fd_account_model',
            old_name='interest',
            new_name='interest_rate',
        ),
        migrations.AddField(
            model_name='fd_account_model',
            name='maturity_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fd_account_model',
            name='maturity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
