# Generated by Django 5.0.4 on 2024-05-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0010_rename_amount_fd_account_model_deposit_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fd_account_model',
            old_name='Deposit_amount',
            new_name='deposit_amount',
        ),
    ]
