# Generated by Django 5.0.4 on 2024-05-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0011_rename_deposit_amount_fd_account_model_deposit_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fd_account_model',
            name='tenure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
