# Generated by Django 5.0.4 on 2024-05-06 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0012_alter_fd_account_model_tenure'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_account_model',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
