# Generated by Django 5.0.4 on 2024-05-07 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0013_fd_account_model_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fd_account_model',
            name='close_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fd_account_model',
            name='close_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
