# Generated by Django 5.0.4 on 2024-05-07 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fixed_deposit', '0015_fd_account_model_current_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fd_account_model',
            name='close_amount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fd_account_model',
            name='maturity_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
