# Generated by Django 5.0.4 on 2024-05-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_transaction_options_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='account',
            field=models.IntegerField(null=True),
        ),
    ]
