# Generated by Django 5.0.4 on 2024-05-05 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_transaction_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user',
            new_name='saving_account',
        ),
    ]
