# Generated by Django 5.0.4 on 2024-05-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_rename_user_transaction_saving_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='account',
            new_name='payer_account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiver_account',
            field=models.IntegerField(null=True),
        ),
    ]
