# Generated by Django 5.0.4 on 2024-05-07 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_rename_account_transaction_payer_account_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountApprove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('saving_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.savings_account')),
            ],
        ),
    ]
