# Generated by Django 5.0.4 on 2024-05-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_accountapprove'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payer_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiver_account',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
