# Generated by Django 5.0.4 on 2024-05-09 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_savings_account_transaction_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savings_account',
            name='transaction_limit',
            field=models.IntegerField(blank=True, default=10000, null=True),
        ),
    ]
