# Generated by Django 5.0.4 on 2024-05-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='personal_email',
            field=models.EmailField(default='am@gmail.com', max_length=100),
        ),
    ]
