# Generated by Django 5.0.4 on 2024-05-10 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_staffprofile_personal_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='personal_email',
            field=models.EmailField(max_length=100),
        ),
    ]
