# Generated by Django 5.0.4 on 2024-05-08 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Loan_data',
        ),
    ]
