# Generated by Django 5.0.4 on 2024-05-08 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loan', '0002_delete_loan_data'),
        ('user', '0005_alter_profile_pan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_account_number', models.CharField(max_length=20, unique=True)),
                ('interest_rate', models.IntegerField(blank=True, null=True)),
                ('tenure', models.CharField(blank=True, max_length=20, null=True)),
                ('loan_amount', models.IntegerField()),
                ('open_date', models.DateField(auto_now_add=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_amount', models.FloatField(blank=True, null=True)),
                ('to_account', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
        ),
    ]
