# Generated by Django 5.0.4 on 2024-05-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0006_loan_interest_period_amount_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan_data',
            old_name='tenure',
            new_name='period',
        ),
    ]
