# Generated by Django 5.0.4 on 2024-05-09 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0007_rename_tenure_loan_data_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_data',
            name='period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
