# Generated by Django 5.0.4 on 2024-05-09 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0008_alter_loan_data_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='emi',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
