# Generated by Django 5.0.4 on 2024-05-09 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0012_alter_loan_data_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan_data',
            name='to_account',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
