# Generated by Django 5.0.4 on 2024-05-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0015_loan_data_close_amount_loan_data_close_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='current_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
