# Generated by Django 5.0.4 on 2024-05-07 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhaar',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='pan',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
