# Generated by Django 5.0.4 on 2024-05-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_aadhaar_profile_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhaar',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pan',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
    ]
