# Generated by Django 5.0.4 on 2024-05-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_profile_aadhaar_alter_profile_pan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pan',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
