# Generated by Django 5.0.4 on 2024-05-10 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_customuser_reset_password_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='aadhaar',
            field=models.CharField(blank=True, default='Male', max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='1998-03-28', null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(default='abk@g.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Male', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='a', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pan',
            field=models.CharField(blank=True, default='Male', max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(blank=True, default=1234567895),
        ),
    ]
